<?php

class DrexCartFunctions {
	
	
	public function getStatesList() {
		return array('AL'=>'Alabama',
				'AK'=>'Alaska',
				'AS'=>'American samoa',
				'AZ'=>'Arizona',
				'AR'=>'Arkansas',
				'CA'=>'California',
				'CO'=>'Colorado',
				'CT'=>'Connecticut',
				'DE'=>'Delaware',
				'DC'=>'District of columbia',
				'FM'=>'Federated states of micronesia',
				'FL'=>'Florida',
				'GA'=>'Georgia',
				'GU'=>'Guam',
				'HI'=>'Hawaii',
				'ID'=>'Idaho',
				'IL'=>'Illinois',
				'IN'=>'Indiana',
				'IA'=>'Iowa',
				'KS'=>'Kansas',
				'KY'=>'Kentucky',
				'LA'=>'Louisiana',
				'ME'=>'Maine',
				'MH'=>'Marshall islands',
				'MD'=>'Maryland',
				'MA'=>'Massachusetts',
				'MI'=>'Michigan',
				'MN'=>'Minnesota',
				'MS'=>'Mississippi',
				'MO'=>'Missouri',
				'MT'=>'Montana',
				'NE'=>'Nebraska',
				'NV'=>'Nevada',
				'NH'=>'New hampshire',
				'NJ'=>'New jersey',
				'NM'=>'New mexico',
				'NY'=>'New york',
				'NC'=>'North carolina',
				'ND'=>'North dakota',
				'MP'=>'Northern mariana islands',
				'OH'=>'Ohio',
				'OK'=>'Oklahoma',
				'OR'=>'Oregon',
				'PW'=>'Palau',
				'PA'=>'Pennsylvania',
				'PR'=>'Puerto rico',
				'RI'=>'Rhode island',
				'SC'=>'South carolina',
				'SD'=>'South dakota',
				'TN'=>'Tennessee',
				'TX'=>'Texas',
				'UT'=>'Utah',
				'VT'=>'Vermont',
				'VI'=>'Virgin islands',
				'VA'=>'Virginia',
				'WA'=>'Washington',
				'WV'=>'West virginia',
				'WI'=>'Wisconsin',
				'WY'=>'Wyoming');
	}
	
}